version: '3.4'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SHADOW_DATABASE_URL=${SHADOW_DATABASE_URL}
      - STORAGE_CONNECTION_STRING=${STORAGE_CONNECTION_STRING}
  
