version: '3.4'

services:
  processor:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SERVICE_BUS_NAMESPACE_CONNECTION_STRING=${SERVICE_BUS_NAMESPACE_CONNECTION_STRING}
      - SERVICE_BUS_NODE_QUEUE_NAME=${SERVICE_BUS_NODE_QUEUE_NAME}

